deps.fabric_loader = "0.19.5"
deps.flashback = ">=0.43.6"
java.release = 25
loomx.loom_version = "1.17-SNAPSHOT"
loomx.loom_remap_plugin = "net.fabricmc.fabric-loom-remap"
loomx.loom_unobf_plugin = "net.fabricmc.fabric-loom"
mc.version = "[VERSIONED]"
mc.targets = "[VERSIONED]"
ffmpeg_natives = "8.1.2-1.5.14"
javacpp_natives = "1.5.14"

["1.21.11"]
mc.version = "1.21.11"
mc.targets = "1.21.11"
deps.fabric_loader = "0.15.10"
deps.flashback = ">=0.39.10"
java.release = 21
ffmpeg_natives = "6.1.1-1.5.10"
javacpp_natives = "1.5.10"

["26.1.2"]
mc.version = "26.1.2"
mc.targets = "26.1.2"
deps.fabric_loader = "0.19.0"
deps.flashback = ">=0.43.3"

["26.2"]
mc.version = "26.2"
mc.targets = "26.2"

["26.3"]
mc.version = "26.3"
mc.targets = "26.3"
